### ISSUE TITLE
Reset password broken

### ISSUE THREAD

**Issue by nodesocket** [overshard/timestrap#18]
I am assuming there needs to be SMTP configuration set to use a 3rd party like Mailgun.

````
Internal Server Error: /password_reset/
Traceback (most recent call last):
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 416, in dispatch
    return super(PasswordResetView, self).dispatch(*args, **kwargs)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 429, in form_valid
    form.save(**opts)
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/contrib/auth/forms.py", line 289, in save
    email, html_email_template_name=html_email_template_name,
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/contrib/auth/forms.py", line 243, in send_mail
    email_message.send()
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 342, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "/home/ubuntu/timestrap/.venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 64, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[24/Apr/2017 01:42:03] "POST /password_reset/ HTTP/1.1" 500 147917
````

**Comment by overshard** [comment]
I have not tested the password reset system at all to be honest! For Heroku this can be done by enabling sendgrid or mailgun and adding a few lines to settings. We do link to the reset password page already though so this should work or be documented. Definitely needs improvement.

**Comment by nodesocket** [comment]
Right. If I forgot the password I set running `createsuperuser` can I just run it again to override?

**Comment by overshard** [comment]
You can create another superuser to then go in and edit your old super user for now yes.
